[project]
name = "wrc-coach"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "folium>=0.20.0",
    "matplotlib>=3.10.7",
    "pandas>=2.3.3",
    "pip>=25.2",
    "scipy>=1.16.2",
]
